Controllers/WarehouseController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Core.Metadata.Edm;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Microsoft.Ajax.Utilities;
using SupplyChainManagement.Models;
using SupplyChainManagement.ViewModels;
using WebGrease.Css.Ast.Selectors;


namespace SupplyChainManagement.Controllers
{
    public class WarehouseController : Controller
    {
        private ApplicationDbContext _context;


        public WarehouseController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();

        }


        // GET: Warehouse
        public ActionResult Index()
        {
            if (Session["username"] != null)
            {
                if (Convert.ToInt32(Session["userrole"].ToString()) != 2)
                {
                    Response.Redirect("~/Home/Index");
                }

            }
            else
            {
                Response.Redirect("~/Home/Index");

            }
            //var products = _context.WarehouseStocks.ToList();
            //var stock = _context.WarehouseStocks;
            //var datasend = new WarehouseProductJoin
            //{
            //    WProducts = products,
            //    WStocks = stock
            //};
            //var products = _context.Wproducts;

            //DbSet<WarehouseStock> warehouseslist = _context.WarehouseStocks;
            //WarehouseProductJoin warehouseProductJoins = new WarehouseProductJoin();
            //List<WarehouseProductJoin> warehouseProductJoinslist = warehouseslist.Select(x => new WarehouseProductJoin
            //{
            //    PId = x.WarehouseProduct.PId, Name = x.WarehouseProduct.Name, Price = x.WarehouseProduct.Price,
            //    ShelveNo = x.ShelveNo, Quantity = x.Quantity, Type = x.WarehouseProduct.Type,
            //    Description = x.WarehouseProduct.Description
            //}).ToList();

            //warehouseProductJoins.WProducts = _context.WarehouseProducts.ToList();
            //warehouseProductJoins.WStocks = _context.WarehouseStocks.ToList();



            List<WarehouseProduct> products = _context.WarehouseProducts.ToList();
            List<WarehouseStock> stocks = _context.WarehouseStocks.ToList();
            var StockList = (from s in stocks
                             join p in products on s.ProductID equals p.PId
                             where s.Status == 0
                             select new WarehouseProductJoin()
                             {
                                 Wproducts = p,
                                 WStock = s

                             }).ToList();

            return View(StockList);
            //}
        }

        public ActionResult AllProducts()
        {
            var products = _context.WarehouseProducts.ToList();
            var productlist = (from p in products
                               where p.Status == 0
                               select new WarehouseProduct()
                               {
                                   PId = p.PId,
                                   Name = p.Name,
                                   Description = p.Description,
                                   Price = p.Price,
                                   Category = p.Category,
                                   Type = p.Type

                               }).ToList();
            return View(productlist);
        }


        public ActionResult AddProduct()
        {
            return View();

        }


        [HttpPost]
        public ActionResult AddProduct(WarehouseProductJoin warehouseProductJoin)
        {
            var products = new WarehouseProduct();
            var stock = new WarehouseStock();

            products.PId = warehouseProductJoin.Wproducts.PId.ToUpper();
            products.Name = warehouseProductJoin.Wproducts.Name;
            products.Price = warehouseProductJoin.Wproducts.Price;
            products.Type = Request.Form["PType"];
            products.Category = Request.Form["PCategory"];
            products.Description = warehouseProductJoin.Wproducts.Description;

            stock.ProductID = warehouseProductJoin.Wproducts.PId;
            stock.Quantity = warehouseProductJoin.WStock.Quantity;
            stock.ShelveNo = warehouseProductJoin.WStock.ShelveNo;

            try
            {
                _context.WarehouseProducts.Add(products);
                _context.WarehouseStocks.Add(stock);
                _context.SaveChanges();
            }
            catch
            {
                return View();
            }
            return Redirect("~/Warehouse/Index");
        }



        public ActionResult Orders()
        {
            List<WarehouseOrder> orders = _context.WarehouseOrders.ToList();
            List<WarehouseOrderDetail> details = _context.WarehouseOrderDetails.ToList();
            List<WarehouseOrderType> type = _context.WarehouseOrderTypes.ToList();
            var OrderList = (from o in orders
                             join d in details on o.OId equals d.OrderID
                             join t in type on o.OId equals t.OId
                             where t.Status == 0
                             orderby o.OId descending 
                             select new WarehouseOrderJoin()
                             {
                                 WarehouseOrderj = o,
                                 WarehouseOrderDetailj = d,
                                 WarehouseOrderTypej = t
                             }).ToList();

            return View(OrderList);
        }

        public ActionResult BoundIn()
        {
            List<WarehouseOrder> orders = _context.WarehouseOrders.ToList();
            List<WarehouseOrderDetail> details = _context.WarehouseOrderDetails.ToList();
            List<WarehouseOrderType> type = _context.WarehouseOrderTypes.ToList();
            var OrderList = (from o in orders
                             join d in details on o.OId equals d.OrderID
                             join t in type on o.OId equals t.OId
                             where t.type == 1
                             select new WarehouseOrderJoin()
                             {
                                 WarehouseOrderj = o,
                                 WarehouseOrderDetailj = d,
                                 WarehouseOrderTypej = t
                             }).ToList();

            return View(OrderList);
        }

        public ActionResult BoundOut()
        {

            List<WarehouseOrder> orders = _context.WarehouseOrders.ToList();
            List<WarehouseOrderDetail> details = _context.WarehouseOrderDetails.ToList();
            List<WarehouseOrderType> type = _context.WarehouseOrderTypes.ToList();
            var OrderList = (from o in orders
                             join d in details on o.OId equals d.OrderID
                             join t in type on o.OId equals t.OId
                             where t.type == 2
                             select new WarehouseOrderJoin()
                             {
                                 WarehouseOrderj = o,
                                 WarehouseOrderDetailj = d,
                                 WarehouseOrderTypej = t
                             }).ToList();
            return View(OrderList);
        }

        public ActionResult SearchProduct()
        {
            return View();
        }

        [Route("warehouse/edit/{id}")]
        public ActionResult Edit(string id)
        {

            var product = _context.WarehouseProducts.SingleOrDefault(p => p.PId == id);
            var stock = _context.WarehouseStocks.SingleOrDefault(s => s.ProductID == id);
            if (product == null)
            {
                return HttpNotFound();
            }
            var warehouseProductJoin = new WarehouseProductJoin();
            if (stock == null)
            {
                int quantity = 0;
                warehouseProductJoin.Wproducts = product;
                WarehouseStock warehouseStock = new WarehouseStock();
                warehouseStock.Quantity = quantity;
                warehouseStock.ShelveNo = "N/A";
                warehouseProductJoin.WStock = warehouseStock;
            }
            else
            {
                warehouseProductJoin.Wproducts = product;
                warehouseProductJoin.WStock = stock;
            }
            return View(warehouseProductJoin);

        }


        [HttpPost]
        public ActionResult Update(WarehouseProductJoin warehouseProductJoin)
        {

            var productInDb = _context.WarehouseProducts.Single(p => p.PId == warehouseProductJoin.Wproducts.PId);
            var stockInDb = _context.WarehouseStocks.Single(s => s.ProductID == warehouseProductJoin.Wproducts.PId);
            productInDb.PId = warehouseProductJoin.Wproducts.PId;
            productInDb.Name = warehouseProductJoin.Wproducts.Name;
            productInDb.Price = warehouseProductJoin.Wproducts.Price;
            productInDb.Type = Request.Form["PType"];
            productInDb.Category = Request.Form["PCategory"];
            productInDb.Description = warehouseProductJoin.Wproducts.Description;
            stockInDb.Quantity = warehouseProductJoin.WStock.Quantity;
            stockInDb.ShelveNo = warehouseProductJoin.WStock.ShelveNo;
            _context.SaveChanges();
            return Redirect("~/Warehouse/Index");

        }

        public ActionResult AddOrder()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddOrder(WarehouseOrderJoin warehouseOrderJoin)
        {

            var OrderId = Request.Form["OrderID"];
            var date = Request.Form["date"];

Views/Warehouse/AddVendorOrder.cshtml
@model SupplyChainManagement.Models.WarehouseVendorRequest

@{
    ViewBag.Title = "Add Vendor Order";
}

<div class="page-content d-flex align-items-stretch">
    @Html.Partial("_navbar")
    <div class="content-inner">
        @Html.Partial("_header")
        <section class="dashboard-counts no-padding-bottom">
            <div class="container-fluid">
                <div class="col-12" style="margin: auto; width: 90%;">
                    <div class="row bg-white has-shadow">
                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <div class="card">

                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="form-horizontal">
                                        <h4>Add Vendor Order</h4>
                                        <hr />
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                        <div class="form-group row">
                                            <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                                <strong>
                                                    @Html.LabelFor(model => model.OID)
                                                </strong>
                                            </label>
                                            <div class="col-sm-9">
                                                @Html.TextBoxFor(model => model.OID, new { @class = "form-control", required = "required", @autofocus = "autofocus" })
                                                @Html.ValidationMessageFor(model => model.OID, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                                <strong>
                                                    @Html.LabelFor(model => model.Pid)
                                                </strong>
                                            </label>
                                            <div class="col-sm-9">
                                                @Html.TextBoxFor(model => model.Pid, new { @class = "form-control", required = "required", id = "PIDtxtbox" })
                                                <div id="suggesstion-box" style="overflow: auto; background: white; position: absolute; z-index: 99;"> </div>
                                                @Html.ValidationMessageFor(model => model.Pid, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                                <strong>
                                                    @Html.LabelFor(model => model.Quantity)
                                                </strong>
                                            </label>
                                            <div class="col-sm-9">
                                                @Html.TextBoxFor(model => model.Quantity, new { type = "number", min = 1, @class = "form-control", required = "required" })
                                                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <div class="col-sm-4 offset-sm-3">
                                                <button type="button" class="btn btn-secondary" onclick="window.location.href = 'WVendor'">Cancel</button>
                                                <button type="submit" class="btn btn-primary">Confirm Order</button>
                                            </div>
                                        </div>

                                    </div>
                                }

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <br />
        <br />
        <script>
            $(document).ready(function () {
                $("#suggesstion-box").css("display", "none");
                $("#PIDtxtbox").keyup(function () {
                    if ($("#suggesstion-box").val() == "") {
                        $("#suggesstion-box").html("");
                    }
                    $("#suggesstion-box").html("");

                    $.ajax({
                        url: "/Api/ProductSuggestion/" + $("#PIDtxtbox").val(),
                        type: "Get",
                        success: function (data) {
                            $("#suggesstion-box").show();
                            $.each(data, function (index) {
                                console.log(data[index])
                                $("#suggesstion-box").append("<p onclick = setValue('"+data[index].PId+"')> PID: "+ data[index].PId + " Name: "+ data[index].Name + "</p>");
                            });
                        },
                        error: function (xhr) {
                            console.log("Error");
                        }

                    });
                });

            });
            function setValue(id) {
                document.getElementById("PIDtxtbox").value = id;
                document.getElementById("suggesstion-box").innerHTML = "";
                document.getElementById("suggesstion-box").hide = true;

            }
           
            for (var i = 1; i <= 10; i++) {
                document.getElementById(i).className = "";
            }
            document.getElementById("three").click();
            document.getElementById("10").className = "active";
        </script>
        @Html.Partial("_footer")
    </div>
</div>

Views/Warehouse/BoundIn.cshtml
@model List<SupplyChainManagement.ViewModels.WarehouseOrderJoin>
@{
    ViewBag.Title = "Orders";
}
<div class="page-content d-flex align-items-stretch">
    @Html.Partial("_navbar")
    <div class="content-inner">
        @Html.Partial("_header")
        <section class="dashboard-counts">
            <div class="container-fluid">
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="card">
                            <div class="TableHeading">
                                <h2>SENDING WAREHOUSE ORDERS</h2>
                            </div>
                            <div class="body">
                                <div class="table-responsive">
                                    <table class="table table-bordered table-striped table-hover" id="products">
                                        <thead>
                                            <tr>
                                                <th>ID #</th>
                                                <th>PRODUCT ID</th>
                                                <th>QUANTITY</th>
                                                <th>PRICE</th>
                                                <th>DATE</th>
                                                <th>TYPE</th>
                                                <th>SENDER</th>
                                                <th>RECEIVER</th>
                                                <th>Edit/Delete</th>

                                            </tr>
                                        </thead>
                                        <tfoot>
                                            <tr>
                                                <th>ID #</th>
                                                <th>PRODUCT ID</th>
                                                <th>QUANTITY</th>
                                                <th>PRICE</th>
                                                <th>DATE</th>
                                                <th>TYPE</th>
                                                <th>SENDER</th>
                                                <th>RECEIVER</th>
                                                <th>Edit/Delete</th>
                                            </tr>
                                        </tfoot>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                if (item.WarehouseOrderTypej.Status == 0)
                                                {
                                                    <tr>
                                                        <th>@item.WarehouseOrderj.OId</th>
                                                        <td>@item.WarehouseOrderj.PId</td>
                                                        <td>@item.WarehouseOrderj.PQuantity</td>
                                                        <td>@item.WarehouseOrderj.TotalPrice</td>
                                                        <td>@item.WarehouseOrderj.Date</td>
                                                        <td>InBound</td>
                                                        <td>@item.WarehouseOrderDetailj.Sender</td>
                                                        <td>@item.WarehouseOrderDetailj.Receiver</td>
                                                        <td>
                                                            <button onclick="window.location.href = '/Warehouse/editorder/@item.WarehouseOrderj.OId'" type="button" class="btn btn-primary">Edit</button>
                                                            <button data-product-id="@item.WarehouseOrderj.OId" type="button" class="btn btn-danger js-delete">Delete</button>
                                                        </td>
                                                    </tr>

                                                }
                                            }

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        @Html.Partial("_footer")
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#products').dataTable({
            aLengthMenu: [
                [-1, 10, 25, 75, 100],
                ["All", 10, 25, 75, 100]
            ],
            iDisplayLength: -1
        });
        $("#orders .js-delete").on("click",
            function () {
                var btnRef = $(this);
                var btn = $(this).attr("data-product-id");
                bootbox.confirm("Are you sure you want to delete this product?",
                    function (result) {
                        if (result) {
                            $.ajax({
                                url: "/Api/WarehousesOrder/" + btn,
                                method: "DELETE",
                                success: function () {
                                    location.reload();
                                },
                                error: function (xhr) {
                                    console.log(xhr);
                                }
                            });
                        }
                    });
            });
    });

    for (var i = 1; i <= 10; i++) {
        document.getElementById(i).className = "";
    }
    document.getElementById("two").click();
    document.getElementById("6").className = "active";
</script>

Views/Warehouse/EditVOrder.cshtml
@model SupplyChainManagement.Models.WarehouseVendorRequest

@{
    ViewBag.Title = "Update vendor order";
}

<div class="page-content d-flex align-items-stretch">
    @Html.Partial("_navbar")
    <div class="content-inner">
        @Html.Partial("_header")
        <section class="dashboard-counts no-padding-bottom">
            <div class="container-fluid">
                <div class="col-12" style="margin: auto; width: 90%;">
                    <div class="row bg-white has-shadow">
                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <div class="card">

                                @using (Html.BeginForm("EditVendorOrder", "Warehouse"))
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="form-horizontal">
                                        <h4>Update vendor order</h4>
                                        <hr />
                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                        <div class="form-group row">
                                            <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                                <strong>
                                                    @Html.LabelFor(model => model.OID)
                                                </strong>
                                            </label>
                                            <div class="col-sm-9">
                                                @Html.TextBoxFor(model => model.OID, new { @class = "form-control", required = "required", @readonly = "readonly" })
                                                @Html.ValidationMessageFor(model => model.OID, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                                <strong>
                                                    @Html.LabelFor(model => model.Pid)
                                                </strong>
                                            </label>
                                            <div class="col-sm-9">
                                                @Html.TextBoxFor(model => model.Pid, new { @class = "form-control", required = "required" })
                                                @Html.ValidationMessageFor(model => model.Pid, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                                <strong>
                                                    @Html.LabelFor(model => model.Quantity)
                                                </strong>
                                            </label>
                                            <div class="col-sm-9">
                                                @Html.TextBoxFor(model => model.Quantity, new { type = "number", min = 0, @class = "form-control", required = "required" })
                                                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <div class="col-sm-4 offset-sm-3">
                                                <button type="submit" class="btn btn-primary">Update Order</button>
                                            </div>
                                        </div>

                                    </div>
                                }

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <br />
        <br />

        @Html.Partial("_footer")
    </div>
</div>

Views/Warehouse/OrderError.cshtml
@model IEnumerable<SupplyChainManagement.Models.WarehouseProduct>
@{
    ViewBag.Title = "SearchProduct";
}
<div class="page-content d-flex align-items-stretch">
    @Html.Partial("_navbar")
    <div class="content-inner">
        @Html.Partial("_header")

        <section class="dashboard-counts no-padding-bottom">
            <div class="container-fluid">
                <div class="row bg-white has-shadow">
                    <div class="col-xl-10 col-sm-10">
                        <h1> Error while placing order, Please try again </h1>
                    </div>
                </div>
            </div>
        </section>
       
        <br />

        &nbsp;

        <script type="text/javascript">
            
            for (var i = 1; i <= 10; i++) {
                document.getElementById(i).className = "";
            }
            document.getElementById("two").click();
            document.getElementById("7").className = "active";
        </script>
        @Html.Partial("_footer")
    </div>
</div>

Views/Warehouse/PrintOrderReceipt.cshtml
@model IEnumerable<SupplyChainManagement.Models.WarehouseOrder>
@{
    ViewBag.Title = "Order Receipt";
}
<div class="page-content d-flex align-items-stretch">
    @Html.Partial("_navbar")
    <div class="content-inner">
        @Html.Partial("_header")

        <section class="dashboard-counts no-padding-bottom">
            <div class="container-fluid">
                <div class="col-12" style="margin: auto; width: 70%;">
                    <div class="row bg-white has-shadow">
                        <div class="col-xl-10 col-sm-10">
                            <div class="TableHeading">
                                <h2>Search Order:</h2>
                            </div>

                            <div class="form-group">
                                <input type="text" list="browsers" id="searchbox" class="form-control" placeholder="Search Product" style="min-width: 80%; margin-left: 10%; margin-right: 10%;">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="dashboard-counts no-padding-bottom" style="padding-top:10px !important" id="searchSection">
            <div class="container-fluid">
                <div class="col-12" style="margin: auto; width: 70%;">
                    <div class="row bg-white has-shadow">
                        <div class="col-xl-10 col-sm-10">
                            <div style="min-width: 80%; margin-left: 10%; margin-right: 10%;" id="searchback">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <br />



        &nbsp;

        <script type="text/javascript">
            $(document).ready(function () {
                $("#searchSection").css("display", "none");
                $("#searchbox").keyup(function () {
                    if ($("#searchbox").val() == "") {
                        $("#searchback").html("");
                    }
                    $("#searchback").html("");
                    $("#searchSection").css("display", "block");
                    var prevId = 0;
                    var newId = 0;
                    $.ajax({
                        url: "/Api/SearchOrder/" + $("#searchbox").val(),
                        type: "Get",
                        success: function (data) {
                            $.each(data, function (index) {
                                newId = data[index].OId;
                                if (newId != prevId) {
                                    prevId = data[index].OId;
                                    $("#searchback")
                                        .append("<a href='/Warehouse/OrderReceipt/" + data[index].OId + "'><p>Order ID: " + data[index].OId + " &nbsp; | &nbsp; Date: " + data[index].Date + "</p></a><br />");
                                }
                            });
                        },
                        error: function (xhr) {
                            console.log("Error");
                        }

                    });
                });
            });

            for (var i = 1; i <= 10; i++) {
                document.getElementById(i).className = "";
            }
            document.getElementById("two").click();
            document.getElementById("8").className = "active";
        </script>
        @Html.Partial("_footer")
    </div>
</div>

Views/Warehouse/_footer.cshtml
<footer class="main-footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <p>&copy; @DateTime.Now.Year Final Year Project - Supply chan management</p>
            </div>

        </div>
    </div>
</footer>

Views/Warehouse/_header.cshtml
<header class="page-header">
    <div class="container-fluid">
        <h2 class="no-margin-bottom">Warehouse Management</h2>
    </div>
</header>