Controllers/Api/ProductionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Microsoft.Ajax.Utilities;
using SupplyChainManagement.Models;
using SupplyChainManagement.ViewModels;

namespace SupplyChainManagement.Controllers.Api
{
    public class ProductionsController : ApiController
    {
        private ApplicationDbContext _context;

        public ProductionsController()
        {
            _context = new ApplicationDbContext();
        }

        [Route("Api/Productions/{id}")]
        [HttpDelete]
        //PUT /api/Productions/1
        public void ProductionsDelete(string id)
        {
            var productionOrder = _context.ProductionOrders.SingleOrDefault(o => o.Id == id);
            List<ProductionRawMaterial> orderraw = _context.ProductionRawMaterial.ToList();
            var orderrawInDb = _context.ProductionRawMaterial.Where(or => or.OId == id).ToList();

            if (productionOrder == null)
            {
                throw new HttpResponseException(HttpStatusCode.NotFound);
            }

            _context.ProductionRawMaterial.RemoveRange(orderrawInDb);
            _context.ProductionOrders.Remove(productionOrder);
            _context.SaveChanges();


        }
    }
}

Controllers/ProductionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Http;
using System.Web.Http.ModelBinding.Binders;
using System.Web.Mvc;
using SupplyChainManagement.Models;
using SupplyChainManagement.ViewModels;

namespace SupplyChainManagement.Controllers
{
    public class ProductionController : Controller
    {
        private ApplicationDbContext _context;

        public ProductionController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();

        }

        // GET: Production
        public ActionResult Index()
        {
            if (Session["username"] != null)
            {
                if (Convert.ToInt32(Session["userrole"].ToString()) != 4)
                {
                    Response.Redirect("~/Home/Index");
                }

            }
            else
            {
                Response.Redirect("~/Home/Index");

            }

            var POrders = _context.ProductionOrders.ToList();

            return View(POrders);
        }

        public ActionResult addOrder()
        {
            return View();
        }

        [System.Web.Mvc.HttpPost]
        public ActionResult addOrder(ProductionAddOrder Item)
        {
            var order = new ProductionOrder();
            var raw = new ProductionRawMaterial();
            order = Item.productionOrder;
            _context.ProductionOrders.Add(order);
            List<string> listRaw = (Item.productionRawMaterial.PId).Split(',').ToList<string>();
            List<string> quantityRaw = (Item.productionRawMaterial.Quantity).Split(',').ToList<string>();
            for (var x = 0; x < listRaw.Count(); x++)
            {
                raw.OId = Item.productionOrder.Id;
                raw.PId = listRaw[x];
                raw.Quantity = quantityRaw[x];
                _context.ProductionRawMaterial.Add(raw);
                raw = new ProductionRawMaterial();
            }

            _context.SaveChanges();
            return Redirect("Index");
        }

        [System.Web.Mvc.Route("Production/Edit/{id}")]
        public ActionResult Edit(string id)
        {
            var orderInDb = new ProductionAddOrder();

            var order = _context.ProductionOrders.SingleOrDefault(o => o.Id == id);

            var orderrawInDb = _context.ProductionRawMaterial.Where(or => or.OId == id).ToList();
            List<ProductionRawMaterial> list = new List<ProductionRawMaterial>();
            list = orderrawInDb;

            string products = "";
            string quantity = "";

            foreach (var item in list)
            {
                products = products + item.PId + ",";
                quantity = quantity + item.Quantity + ",";
            }

            ProductionRawMaterial prm = new ProductionRawMaterial();
            prm.Quantity = quantity;
            prm.PId = products;
            prm.OId = id;
            prm.SNO = 0;
            orderInDb.productionOrder = order;
            orderInDb.productionRawMaterial = prm;

            return View(orderInDb);
        }

        [System.Web.Mvc.HttpPost]
        public ActionResult UpdateOrder(ProductionAddOrder production)
        {
            var orderrawInDb = _context.ProductionRawMaterial.Where(or => or.OId == production.productionOrder.Id).ToList();
            _context.ProductionRawMaterial.RemoveRange(orderrawInDb);
            var order = _context.ProductionOrders.SingleOrDefault(o => o.Id == production.productionOrder.Id);
            order.PId = production.productionOrder.PId;
            order.ExpectedDate = production.productionOrder.ExpectedDate;
            order.StartDate = production.productionOrder.StartDate;
            order.Status = production.productionOrder.Status;
            order.Title = production.productionOrder.Title;
            _context.SaveChanges();
            try
            {
                var raw = new ProductionRawMaterial();
                List<string> listRaw = (production.productionRawMaterial.PId).Split(',').ToList<string>();
                List<string> quantityRaw = (production.productionRawMaterial.Quantity).Split(',').ToList<string>();
                for (var x = 0; x < listRaw.Count(); x++)
                {
                    if (listRaw[x] != null)
                    {
                        raw.OId = production.productionOrder.Id;
                        raw.PId = listRaw[x];
                        raw.Quantity = quantityRaw[x];
                        _context.ProductionRawMaterial.Add(raw);
                        _context.SaveChanges();
                        raw = new ProductionRawMaterial();
                    }
                }
            }
            catch (Exception e)
            {
                return Redirect("~/Production/Index");
            }

            return Redirect("~/Production/Index");

        }

        public ActionResult CompleteOrders()
        {

            var POrders = _context.ProductionOrders.Where(o => o.Status.Equals("Completed")).ToList();
            return View(POrders);
        }

        public ActionResult InProgressOrders()
        {

            var POrders = _context.ProductionOrders.Where(o => o.Status.Equals("InProgress")).ToList();
            return View(POrders);
        }

    }

}

Views/Production/CompleteOrders.cshtml
@model IEnumerable<SupplyChainManagement.Models.ProductionOrder>
@{
    ViewBag.Title = "Index";
}

<div class="page-content d-flex align-items-stretch">
    @Html.Partial("_navbar")
    <div class="content-inner">
        @Html.Partial("_header")
        <section class="dashboard-counts">
            <div class="container-fluid">
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="card">
                            <div class="TableHeading">
                                <h2>Completed PRODUCTION ORDERS</h2>
                                <button id="printBtn" onclick="printBtn()" style="position: absolute; right: 35px; top:15px; background: transparent; background-repeat: no-repeat; border: none; outline: none; height: 40px; width: 40px;">
                                    <img src="~/Content/img/print-icon.png" width="38px" height="38px" />
                                </button>
                            </div>
                            <div class="body">
                                <div class="table-responsive">
                                    <table class="table table-bordered table-striped table-hover js-basic-example dataTable" id="orders">
                                        <thead>
                                            <tr>
                                                <th>ID #</th>
                                                <th>TITLE</th>
                                                <th>START DATE</th>
                                                <th>EXPECTED DATE</th>
                                                <th>FINAL PRODUCT</th>
                                                <th>STATUS</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tfoot>
                                            <tr>
                                                <th>ID #</th>
                                                <th>TITLE</th>
                                                <th>START DATE</th>
                                                <th>EXPECTED DATE</th>
                                                <th>FINAL PRODUCT</th>
                                                <th>STATUS</th>
                                                <th></th>
                                            </tr>
                                        </tfoot>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <th>@item.Id</th>
                                                    <td>@item.Title</td>
                                                    <td>@item.StartDate</td>
                                                    <td>@item.ExpectedDate</td>
                                                    <td>@item.PId</td>
                                                    <td>@item.Status</td>
                                                    <td>
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <script type="text/javascript">
            $(document).ready(function () {
                $("#orders .js-delete").on("click",
                    function () {
                        var btnRef = $(this);
                        var btn = $(this).attr("data-product-id")
                        bootbox.confirm("Are you sure you want to delete this product?",
                            function (result) {
                                if (result) {
                                    $.ajax({
                                        url: "/Api/Productions/" + btn,
                                        method: "DELETE",
                                        success: function () {
                                            btnRef.parents("tr").remove();
                                        },
                                        error: function (xhr) {
                                            console.log(xhr);
                                        }
                                    });
                                }
                            });
                    });
            });

            for (var i = 1; i <= 10; i++) {
                document.getElementById(i).className = "";
            }

            function printBtn() {
                var JsonArray = [];
                @foreach (var item in Model)
                {

                    @:JsonArray.push({ OrderID: '@item.Id', Name: '@item.Title', StartDate: '@item.StartDate', EndDate: '@item.ExpectedDate', PID: '@item.PId', Status: '@item.Status' });
                }
                printJS({
                    header: '<h3 class="PrintHeader">Current Inventory</h3>',
                    printable: JsonArray,
                    properties: [
                        { field: 'OrderID', displayName: 'Order ID' },
                        { field: 'Name', displayName: 'Title' },
                        { field: 'StartDate', displayName: 'Start Date' },
                        { field: 'EndDate', displayName: 'Expected Date' },
                        { field: 'PID', displayName: 'Final Product' },
                        { field: 'Status', displayName: 'Status' },

                    ],
                    type: 'json',
                    style: '.PrintHeader { font-size: 30px; font-family: sans-serif;}'

                });
                console.log();
            }
        </script>

        <script>
            document.getElementById("1").className = "";
            document.getElementById("2").className = "active";
            document.getElementById("3").className = "";
        </script>
        <br />
        <br />
        @Html.Partial("_footer")
    </div>
</div>

Views/Production/Edit.cshtml
@model SupplyChainManagement.ViewModels.ProductionAddOrder

@{
    ViewBag.Title = "Edit Production Order";
    List<SelectListItem> orderstatus = new List<SelectListItem>();
    orderstatus.Add(new SelectListItem
    {
        Text = "Completed",
        Value = "Completed"
    });

    orderstatus.Add(new SelectListItem
    {
        Text = "InProgress",
        Value = "InProgress"
    });
}

<div class="page-content d-flex align-items-stretch">
    @Html.Partial("_navbar")
    <div class="content-inner">
        @Html.Partial("_header")
        <section class="dashboard-counts no-padding-bottom">
            <div class="container-fluid">
                <div class="row bg-white has-shadow">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="card">

                            @using (Html.BeginForm("UpdateOrder", "Production"))
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-horizontal">
                                    <h4>EDIT PRODUCTION ORDER</h4>
                                    <hr />
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                @Html.LabelFor(model => model.productionOrder.Id)
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            @Html.TextBoxFor(model => model.productionOrder.Id, new { @class = "form-control", required = "required"})
                                            @Html.ValidationMessageFor(model => model.productionOrder.Id, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                @Html.LabelFor(model => model.productionOrder.PId)
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            @Html.TextBoxFor(model => model.productionOrder.PId, new { @class = "form-control", required = "required" })
                                            @Html.ValidationMessageFor(model => model.productionOrder.PId, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                @Html.LabelFor(model => model.productionOrder.Title)
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            @Html.TextBoxFor(model => model.productionOrder.Title, new { @class = "form-control", required = "required" })
                                            @Html.ValidationMessageFor(model => model.productionOrder.Title, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                @Html.LabelFor(model => model.productionOrder.StartDate)
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            @Html.TextBoxFor(model => model.productionOrder.StartDate, new { @class = "form-control", required = "required" })
                                            @Html.ValidationMessageFor(model => model.productionOrder.StartDate, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                @Html.LabelFor(model => model.productionOrder.ExpectedDate)
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            @Html.TextBoxFor(model => model.productionOrder.ExpectedDate, new { @class = "form-control", required = "required" })
                                            @Html.ValidationMessageFor(model => model.productionOrder.ExpectedDate, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                @Html.LabelFor(model => model.productionOrder.Status)
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            @Html.DropDownListFor(model => model.productionOrder.Status, orderstatus, "Select order status", new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.productionOrder.Status, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                @Html.LabelFor(model => model.productionRawMaterial.PId)
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            @Html.TextBoxFor(model => model.productionRawMaterial.PId, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.productionRawMaterial.PId, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                @Html.LabelFor(model => model.productionRawMaterial.Quantity)
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            @Html.TextBoxFor(model => model.productionRawMaterial.Quantity, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.productionRawMaterial.Quantity, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <div class="col-sm-4 offset-sm-3">
                                            <button type="submit" class="btn btn-primary">Update Order</button>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <br />
        <br />

        @Html.Partial("_footer")
    </div>
</div>

Views/Production/InProgressOrders.cshtml
@model IEnumerable<SupplyChainManagement.Models.ProductionOrder>
@{
    ViewBag.Title = "Index";
}

<div class="page-content d-flex align-items-stretch">
    @Html.Partial("_navbar")
    <div class="content-inner">
        @Html.Partial("_header")
        <section class="dashboard-counts">
            <div class="container-fluid">
                <div class="row clearfix">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="card">
                            <div class="TableHeading">
                                <h2>InProgress PRODUCTION ORDERS</h2>
                                <button id="printBtn" onclick="printBtn()" style="position: absolute; right: 35px; top:15px; background: transparent; background-repeat: no-repeat; border: none; outline: none; height: 40px; width: 40px;">
                                    <img src="~/Content/img/print-icon.png" width="38px" height="38px" />
                                </button>
                            </div>
                            <div class="body">
                                <div class="table-responsive">
                                    <table class="table table-bordered table-striped table-hover js-basic-example dataTable" id="orders">
                                        <thead>
                                            <tr>
                                                <th>ID #</th>
                                                <th>TITLE</th>
                                                <th>START DATE</th>
                                                <th>EXPECTED DATE</th>
                                                <th>FINAL PRODUCT</th>
                                                <th>STATUS</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tfoot>
                                            <tr>
                                                <th>ID #</th>
                                                <th>TITLE</th>
                                                <th>START DATE</th>
                                                <th>EXPECTED DATE</th>
                                                <th>FINAL PRODUCT</th>
                                                <th>STATUS</th>
                                                <th></th>
                                            </tr>
                                        </tfoot>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <th>@item.Id</th>
                                                    <td>@item.Title</td>
                                                    <td>@item.StartDate</td>
                                                    <td>@item.ExpectedDate</td>
                                                    <td>@item.PId</td>
                                                    <td>@item.Status</td>
                                                    <td>
                                                        <button onclick="window.location.href = '/Production/Edit/@item.Id'" type="button" class="btn btn-primary">Edit</button>

                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <script type="text/javascript">
            $(document).ready(function () {
                $("#orders .js-delete").on("click",
                    function () {
                        var btnRef = $(this);
                        var btn = $(this).attr("data-product-id")
                        bootbox.confirm("Are you sure you want to delete this product?",
                            function (result) {
                                if (result) {
                                    $.ajax({
                                        url: "/Api/Productions/" + btn,
                                        method: "DELETE",
                                        success: function () {
                                            btnRef.parents("tr").remove();
                                        },
                                        error: function (xhr) {
                                            console.log(xhr);
                                        }
                                    });
                                }
                            });
                    });
            });

             for (var i = 1; i <= 10; i++) {
                document.getElementById(i).className = "";
            }

            function printBtn() {
                var JsonArray = [];
                @foreach (var item in Model)
                {

                    @:JsonArray.push({ OrderID: '@item.Id', Name: '@item.Title', StartDate: '@item.StartDate', EndDate: '@item.ExpectedDate', PID: '@item.PId', Status: '@item.Status' });
                }
                printJS({
                    header: '<h3 class="PrintHeader">Current Inventory</h3>',
                    printable: JsonArray,
                    properties: [
                        { field: 'OrderID', displayName: 'Order ID' },
                        { field: 'Name', displayName: 'Title' },
                        { field: 'StartDate', displayName: 'Start Date' },
                        { field: 'EndDate', displayName: 'Expected Date' },
                        { field: 'PID', displayName: 'Final Product' },
                        { field: 'Status', displayName: 'Status' },

                    ],
                    type: 'json',
                    style: '.PrintHeader { font-size: 30px; font-family: sans-serif;}'

                });
                console.log();

            }

        </script>

        <script>
            document.getElementById("1").className = "";
            document.getElementById("2").className = "";
            document.getElementById("3").className = "active";
        </script>
        <br />
        <br />
        @Html.Partial("_footer")
    </div>
</div>

Views/Production/_footer.cshtml
<footer class="main-footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <p>&copy; @DateTime.Now.Year Final Year Project - Office interior</p>
            </div>

        </div>
    </div>
</footer>

Views/Production/_header.cshtml
<header class="page-header">
    <div class="container-fluid">
        <h2 class="no-margin-bottom">Production Management</h2>
    </div>
</header>

Views/Production/_navbar.cshtml
<nav class="side-navbar">
    <!-- Sidebar Header-->
    <div class="sidebar-header d-flex align-items-center">
        <div class="avatar"><img src="~/Content/img/dummy-user-img-1.png" alt="..." class="img-fluid rounded-circle"></div>
        <div class="title">
            <h1 class="h4"> @Session["fullname"]</h1>
            <p>Production Admin</p>
        </div>
    </div>
    <!-- Sidebar Navidation Menus-->
    <ul class="list-unstyled">
        <li id="1">
            <a href="~/Production"><i class="icon-padnote"></i> All Orders</a>
        </li>
        <li id="2">
            <a href="~/Production/CompleteOrders"> <i class="icon-padnote"></i>Completed Orders </a>
        </li>
        <li id="3">
            <a href="~/Production/InProgressOrders"> <i class="icon-padnote"></i>InProgress Orders </a>
        </li>
    </ul>
</nav>