Models/VendorOrder.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SupplyChainManagement.Models
{
    public class VendorOrder
    {
        [Key]
        [Display(Name = "Enter vendor ID")]
        public string Id { get; set; }

        [Required]
        [Display(Name = "Enter vendor-order ID")]
        public string OId { get; set; }

        [ForeignKey("Id")]
        public VendorDetail VendorDetails { get; set; }

        [ForeignKey("OId")]
        public VendorOrder VendorOrders { get; set; }
    }
}

Models/WarehouseOrder.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SupplyChainManagement.Models
{
    public class WarehouseOrder
    {
        [Key]
        public int SNo { get; set; }

        [Required(ErrorMessage = "Please enter order ID")]
        [MaxLength(12)]
        [Display(Name = "Enter order id")]
        public string OId { get; set; }

        [Required(ErrorMessage = "Please enter product ID")]
        [MaxLength(5)]
        [Display(Name = "Enter product id")]
        public string PId { get; set; }

        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Only positive number allowed")]
        [Display(Name = "Enter Product Quantity")]
        public int PQuantity { get; set; }

        [Required]
        public float TotalPrice { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Enter Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
        public DateTime Date { get; set; }

        public int Notification { get; set; }

        [ForeignKey("PId")]
        public WarehouseProduct WarehouseProduct { get; set; }

      
    }
}

Models/WarehouseOrderType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;


namespace SupplyChainManagement.Models
{
    public class WarehouseOrderType
    {
        [Required]
        [Key]
        [Display(Name = "Enter Order ID")]
        public string OId { get; set; }

        [Required]
        [Display(Name = "Enter order type")]
        public int type { get; set; }

        [Required]
        public int Status { get; set; }
    }

    public enum type
    {
        Receiving,
        Sending
    }

}

ViewModels/VendorOrderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SupplyChainManagement.Models;

namespace SupplyChainManagement.ViewModels
{
    public class VendorOrderViewModel
    {
        public VendorDetail VendorDetail { get; set; }
        public VendorOrder VendorOrder { get; set; }
        public VendorOrderDetail VendorOrderDetail { get; set; }

    }
}

Controllers/Api/VendorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using SupplyChainManagement.Models;

namespace SupplyChainManagement.Controllers.Api
{
    public class VendorsController : ApiController
    {
        private ApplicationDbContext _context;

        public VendorsController()
        {
            _context = new ApplicationDbContext();
        }

        [Route("Api/Vendors/{id}")]
        [HttpDelete]
        //PUT /api/Vendors/1
        public void ProductionsDelete(string id)
        {
            var vendor = _context.VendorDetails.SingleOrDefault(v => v.VId == id);
            _context.VendorDetails.Remove(vendor);
            _context.SaveChanges();


        }
    }
}

Controllers/VendorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SupplyChainManagement.Models;
using SupplyChainManagement.ViewModels;
using System.Threading.Tasks;
using SendGrid;
using SendGrid.Helpers.Mail;




namespace SupplyChainManagement.Controllers
{
    public class VendorController : Controller
    {



        private ApplicationDbContext _context;


        public VendorController()
        {

            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();

        }
        // GET: Vendor
        public ActionResult Index()
        {
            if (Session["username"] != null)
            {
                if (Convert.ToInt32(Session["userrole"].ToString()) != 3)
                {
                    Response.Redirect("~/Home/Index");
                }
            }
            else
            {
                Response.Redirect("~/Home/Index");

            }
            
            var vendorList = _context.VendorDetails.ToList();
            return View(vendorList);
        }

        public ActionResult VendorOrders()
        {
            List<VendorDetail> vendorlist = _context.VendorDetails.ToList();
            List<VendorOrder> vendororder = _context.VendorOrders.ToList();
            List<VendorOrderDetail> orderDetails = _context.VendorOrderDetails.ToList();
            var finallist = (from vl in vendorlist
                             join vo in vendororder on vl.VId equals vo.Id
                             join od in orderDetails on vo.OId equals od.Id
                             select new VendorOrderViewModel
                             {
                                 VendorDetail = vl,
                                 VendorOrder = vo,
                                 VendorOrderDetail = od
                             }).ToList();

            return View(finallist);
        }

        public ActionResult AddVendor()
        {
            return View();
        }

        [HttpPost]
        public ActionResult InsertVendor(VendorDetail vendorDetail)
        {
            vendorDetail.UserName = Request.Form["uname"];
            _context.VendorDetails.Add(vendorDetail);
            _context.SaveChanges();
            var uD = new UsersDetail();
            uD.UserName = Request.Form["uname"];
            uD.UserPassword = encryptPassword(Request.Form["upass"]);
            uD.FullName = vendorDetail.Name;
            uD.PhoneNumber = vendorDetail.PhoneNumber;
            uD.RoleId = 6;
            _context.UsersDetails.Add(uD);
            _context.SaveChanges();
            return Redirect("~/Vendor/Index");
        }

        [HttpPost]
        public ActionResult UpdateVendor(VendorDetail vendorDetail)
        {
            var vendorInDb = _context.VendorDetails.SingleOrDefault(v => v.VId.Equals(vendorDetail.VId));
            vendorInDb.UserName = vendorDetail.UserName;
            vendorInDb.Address = vendorDetail.Address;
            vendorInDb.Name = vendorDetail.Address;
            vendorInDb.Email = vendorDetail.Address;
            vendorInDb.PhoneNumber = vendorDetail.PhoneNumber;
            _context.SaveChanges();
            var uD = _context.UsersDetails.SingleOrDefault(u => u.UserName.Equals(vendorDetail.UserName));
            uD.UserPassword = encryptPassword(Request.Form["upass"]);
            _context.SaveChanges();
            return Redirect("~/Vendor/Index");
        }

        public static string encryptPassword(string x)
        {
            System.Security.Cryptography.MD5CryptoServiceProvider Md5 = new System.Security.Cryptography.MD5CryptoServiceProvider();
            byte[] dataInByte = System.Text.Encoding.ASCII.GetBytes(x);
            dataInByte = Md5.ComputeHash(dataInByte);
            String md5Hash = System.Text.Encoding.ASCII.GetString(dataInByte);

            return md5Hash;
        }

        [Route("Vendor/EditVendor/{id}")]
        public ActionResult EditVendor(string id)
        {
            var vendorInDb = _context.VendorDetails.SingleOrDefault(v => v.VId == id);
            return View(vendorInDb);
        }

        public ActionResult AddOrder()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddOrder(VendorOrderDetail vendorOrderDetail)
        {
            string hour = DateTime.Now.ToString("HH", System.Globalization.DateTimeFormatInfo.InvariantInfo);
            string min = DateTime.Now.ToString("mm", System.Globalization.DateTimeFormatInfo.InvariantInfo);
            string month = DateTime.Now.ToString("MM", System.Globalization.DateTimeFormatInfo.InvariantInfo);
            string year = DateTime.Now.ToString("yy", System.Globalization.DateTimeFormatInfo.InvariantInfo);
            string OID = "OV" + hour + min + month + year;
            var Order = new VendorOrderDetail();
            Order.Id = OID;
            Order.PId = vendorOrderDetail.PId;
            Order.PQuantity = vendorOrderDetail.PQuantity;
            Order.Price = vendorOrderDetail.Price;
            Order.VendorId = vendorOrderDetail.VendorId;
            Order.Notification = 0;
            _context.VendorOrderDetails.Add(Order);
            _context.SaveChanges();
            return Redirect("~/Vendor/Index");
        }



        public ActionResult WarehouseOrder()
        {
            var orderInDb = _context.WarehouseVendorRequests.ToList();
            return View(orderInDb);
        }


        [Route("Vendor/SendMail/{id}")]
        public ActionResult SendMail(string id)
        {
            var vendorInDb = _context.VendorDetails.SingleOrDefault(v => v.VId == id);
            return View(vendorInDb);
        }

        //[HttpPost]
        //public ActionResult Index(VendorDetail model)
        //{
        //    var em = model.Email;
        //    var name = model.Name;

        //}

        public ActionResult SendMailBtn(VendorDetail v)
        {
            string email = Request.Form["emailId"];
            string message = Request.Form["message"];
            Execute(email, message).Wait(1000);
            //How to add notify.js or sweetAlert.js here or any other notification

            return Redirect("~/Vendor/Index");


        }


        //[HttpGet]
        //public ActionResult SendData(VendorDetail model)
        //{
        //    var name = model.Name;
        //    var email = model.Email;
        //    return View();
        //}


        static async Task Execute(String email, String Message)
        {
            var client = new SendGridClient("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");
            var from = new EmailAddress("061.umair@gmail.com", "vendor employee");

            var to = new EmailAddress(email); // need email, name from model.
            var subject = "From Office Interior";
            var plainTextContent = "content";
            var htmlContent = Message; //msg here from SendMail View.
            var msg = MailHelper.CreateSingleEmail(
                from,
                to,
                subject,
                plainTextContent,
                htmlContent);

            var response = await client.SendEmailAsync(msg);
            //swal({
            //title: "Good job!",
            //    text: "You clicked the button!",
            //    icon: "success",
            //    button: "Aww yiss!",
            //    });
        }




    }
}

Views/Vendor/AddOrder.cshtml
@model SupplyChainManagement.Models.VendorOrderDetail
@{
    ViewBag.Title = "AddVendor";
}

<div class="page-content d-flex align-items-stretch">
    @Html.Partial("_navbar")
    <div class="content-inner">
        @Html.Partial("_header")
        <section class="dashboard-counts no-padding-bottom">
            <div class="container-fluid">
                <div class="row bg-white has-shadow">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="card">

                            @using (Html.BeginForm("AddOrder", "Vendor"))
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-horizontal">
                                    <h4>Add Vendor</h4>
                                    <hr />
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                @Html.LabelFor(model => model.VendorId)
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            @Html.TextBoxFor(model => model.VendorId, new { @class = "form-control", required = "required" })
                                            @Html.ValidationMessageFor(model => model.VendorId, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                @Html.LabelFor(model => model.PId)
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            @Html.TextBoxFor(model => model.PId, new { @class = "form-control", required = "required" })
                                            @Html.ValidationMessageFor(model => model.PId, "", new { @class = "text-danger" })
                                        </div>
                                    </div>


                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                @Html.LabelFor(model => model.PQuantity)
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            @Html.TextBoxFor(model => model.PQuantity, new { @class = "form-control", required = "required" })
                                            @Html.ValidationMessageFor(model => model.PQuantity, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                @Html.LabelFor(model => model.Price)
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            @Html.TextBoxFor(model => model.Price, new { @class = "form-control", required = "required" })
                                            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-4 offset-sm-3">
                                            <button type="button" class="btn btn-secondary" onclick="window.location.href = 'Index'">Cancel</button>
                                            <button type="submit" class="btn btn-primary">Add Order</button>
                                        </div>
                                    </div>

                                </div>
                            }

                        </div>
                    </div>
                </div>
            </div>
        </section>
        <br />
        <br />
        <script>
            for (var i = 1; i <= 5; i++) {
                document.getElementById(i).className = "";
            }
            document.getElementById("5").className = "active";
        </script>
        @Html.Partial("_footer")
    </div>
</div>

Views/Vendor/AddVendor.cshtml
@model SupplyChainManagement.Models.VendorDetail
@{
    ViewBag.Title = "AddVendor";
}

<div class="page-content d-flex align-items-stretch">
    @Html.Partial("_navbar")
    <div class="content-inner">
        @Html.Partial("_header")
        <section class="dashboard-counts no-padding-bottom">
            <div class="container-fluid">
                <div class="row bg-white has-shadow">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="card">

                            @using (Html.BeginForm("InsertVendor", "Vendor"))
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-horizontal">
                                    <h4>Add Vendor</h4>
                                    <hr />
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                @Html.LabelFor(model => model.VId)
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            @Html.TextBoxFor(model => model.VId, new { @class = "form-control", required = "required" })
                                            @Html.ValidationMessageFor(model => model.VId, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                @Html.LabelFor(model => model.Name)
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control", required = "required" })
                                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                Enter UserName:
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            <input type="text" name="uname" id="uname" class="form-control" />
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                Enter Password:
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            <input type="text" name="upass" id="upass" class="form-control" />
                                        </div>
                                    </div>


                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                @Html.LabelFor(model => model.Email)
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            @Html.TextBoxFor(model => model.Email, new { @class = "form-control", required = "required" })
                                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                @Html.LabelFor(model => model.PhoneNumber)
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control", required = "required" })
                                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                @Html.LabelFor(model => model.Address)
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            @Html.TextBoxFor(model => model.Address, new { @class = "form-control", required = "required" })
                                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <div class="col-sm-4 offset-sm-3">
                                            <button type="button" class="btn btn-secondary" onclick="window.location.href = 'Index'">Cancel</button>
                                            <button type="submit" class="btn btn-primary">Add Vendor</button>
                                        </div>
                                    </div>

                                </div>
                            }

                        </div>
                    </div>
                </div>
            </div>
        </section>
        <br />
        <br />
        <script>
            for (var i = 1; i <= 5; i++) {
                document.getElementById(i).className = "";
            }
            document.getElementById("3").className = "active";
        </script>
        @Html.Partial("_footer")
    </div>
</div>

Views/Vendor/EditVendor.cshtml
@model SupplyChainManagement.Models.VendorDetail
@{
    ViewBag.Title = "AddVendor";
    var Username = Model.UserName;
}

<div class="page-content d-flex align-items-stretch">
    @Html.Partial("_navbar")
    <div class="content-inner">
        @Html.Partial("_header")
        <section class="dashboard-counts no-padding-bottom">
            <div class="container-fluid">
                <div class="row bg-white has-shadow">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <div class="card">

                            @using (Html.BeginForm("UpdateVendor", "Vendor"))
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-horizontal">
                                    <h4>Add Vendor</h4>
                                    <hr />
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                @Html.LabelFor(model => model.VId)
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            @Html.TextBoxFor(model => model.VId, new { @class = "form-control", required = "required", @readonly = "readonly"})
                                            @Html.ValidationMessageFor(model => model.VId, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                @Html.LabelFor(model => model.Name)
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control", required = "required" })
                                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                Enter UserName:
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            <input type="text" name="uname" id="uname" class="form-control" readonly="readonly" />
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                Enter Password:
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            <input type="text" name="upass" id="upass" class="form-control" />
                                        </div>
                                    </div>


                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                @Html.LabelFor(model => model.Email)
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            @Html.TextBoxFor(model => model.Email, new { @class = "form-control", required = "required" })
                                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                @Html.LabelFor(model => model.PhoneNumber)
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control", required = "required" })
                                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-3 form-control-label" style="font-size: 18px">
                                            <strong>
                                                @Html.LabelFor(model => model.Address)
                                            </strong>
                                        </label>
                                        <div class="col-sm-9">
                                            @Html.TextBoxFor(model => model.Address, new { @class = "form-control", required = "required" })
                                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <div class="col-sm-4 offset-sm-3">
                                            <button type="button" class="btn btn-secondary" onclick="window.location.href = 'Index'">Cancel</button>
                                            <button type="submit" class="btn btn-primary">Add Vendor</button>
                                        </div>
                                    </div>

                                </div>
                            }

                        </div>
                    </div>
                </div>
            </div>
        </section>
        <br />
        <br />
        <script>
            $(document).ready(function() {
                $('#uname').val("@Username");

            });
        </script>
        @Html.Partial("_footer")
    </div>
</div>

Views/Vendor/_footer.cshtml
<footer class="main-footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <p>&copy; @DateTime.Now.Year Final Year Project - Office interior</p>
            </div>

        </div>
    </div>
</footer>